# -*- coding: utf-8 -*-
"""课题详解与阶段结果说明 PDF - 正文生成（ReportLab）

封面由 html2poster.js 单独渲染，本脚本只产出正文 body.pdf，
最后由 merge 脚本把 cover.pdf 合并为最终文件。
"""
import hashlib
import os
import sys

PDF_SKILL_DIR = r"C:\Users\user\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.0\skills\pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, HRFlowable, Image, KeepTogether,
                                PageBreak, Paragraph, SimpleDocTemplate, Spacer,
                                Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

ROOT = r"D:\zcode-workspace\hepato-gnn-screening"
OUT = os.path.join(ROOT, "reports", "pdf_build", "body.pdf")
FIG = os.path.join(ROOT, "results", "figures")

# ━━ Color Palette (auto-generated by pdf.py palette.generate, seed=42) ━━
ACCENT = colors.HexColor('#1f7692')
TEXT_PRIMARY = colors.HexColor('#1b1a18')
TEXT_MUTED = colors.HexColor('#7a766f')
BG_SURFACE = colors.HexColor('#e5e3df')
BG_PAGE = colors.HexColor('#edecea')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = BG_SURFACE

# ── 字体注册（Windows 系统字体） ──
pdfmetrics.registerFont(TTFont('SimHei', r'C:\Windows\Fonts\simhei.ttf'))
try:
    pdfmetrics.registerFont(TTFont('Microsoft YaHei', r'C:\Windows\Fonts\msyh.ttc', subfontIndex=0))
    pdfmetrics.registerFont(TTFont('Microsoft YaHei-Bold', r'C:\Windows\Fonts\msyhbd.ttc', subfontIndex=0))
    registerFontFamily('Microsoft YaHei', normal='Microsoft YaHei', bold='Microsoft YaHei-Bold')
    HEAD_FONT = 'Microsoft YaHei'
except Exception:
    registerFontFamily('Microsoft YaHei', normal='SimHei', bold='SimHei')
    HEAD_FONT = 'SimHei'
pdfmetrics.registerFont(TTFont('Times New Roman', r'C:\Windows\Fonts\times.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman-Bold', r'C:\Windows\Fonts\timesbd.ttf'))
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman-Bold')

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
MAX_KEEP_HEIGHT = PAGE_H * 0.4
H1_ORPHAN = AVAIL_H * 0.15

# ── 样式 ──
S_H1 = ParagraphStyle('H1', fontName=HEAD_FONT, fontSize=20, leading=28,
                      textColor=ACCENT, spaceBefore=18, spaceAfter=4, wordWrap='CJK')
S_H2 = ParagraphStyle('H2', fontName=HEAD_FONT, fontSize=14.5, leading=21,
                      textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6, wordWrap='CJK')
S_H3 = ParagraphStyle('H3', fontName=HEAD_FONT, fontSize=11.5, leading=17,
                      textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4, wordWrap='CJK')
S_BODY = ParagraphStyle('Body', fontName='SimHei', fontSize=10.5, leading=17.5,
                        textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK',
                        firstLineIndent=21, spaceAfter=6)
S_BODY_NI = ParagraphStyle('BodyNI', parent=S_BODY, firstLineIndent=0)
S_BULLET = ParagraphStyle('Bullet', fontName='SimHei', fontSize=10.5, leading=17,
                          textColor=TEXT_PRIMARY, wordWrap='CJK', leftIndent=16,
                          spaceAfter=3)
S_CAPTION = ParagraphStyle('Caption', fontName='SimHei', fontSize=8.5, leading=12,
                           textColor=TEXT_MUTED, alignment=TA_CENTER,
                           spaceBefore=3, spaceAfter=6, wordWrap='CJK')
S_TH = ParagraphStyle('TH', fontName=HEAD_FONT, fontSize=9.5, leading=13,
                      textColor=colors.white, alignment=TA_CENTER, wordWrap='CJK')
S_TD = ParagraphStyle('TD', fontName='SimHei', fontSize=9, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
S_TDC = ParagraphStyle('TDC', parent=S_TD, alignment=TA_CENTER)
S_QUOTE = ParagraphStyle('Quote', fontName='SimHei', fontSize=10, leading=16.5,
                         textColor=TEXT_PRIMARY, leftIndent=24, wordWrap='CJK',
                         spaceBefore=6, spaceAfter=6)
S_STAT = ParagraphStyle('Stat', fontName=HEAD_FONT, fontSize=20, leading=24,
                        textColor=ACCENT, alignment=TA_CENTER, wordWrap='CJK')
S_STATL = ParagraphStyle('StatL', fontName='SimHei', fontSize=8.5, leading=12,
                         textColor=TEXT_MUTED, alignment=TA_CENTER, wordWrap='CJK')
S_CODE = ParagraphStyle('Code', fontName='SimHei', fontSize=9, leading=14,
                        textColor=TEXT_PRIMARY, wordWrap='CJK', leftIndent=10,
                        spaceAfter=0)
S_TOC0 = ParagraphStyle('TOC0', fontName=HEAD_FONT, fontSize=12, leading=20, leftIndent=6)
S_TOC1 = ParagraphStyle('TOC1', fontName='SimHei', fontSize=10, leading=16, leftIndent=28)
S_TOCTITLE = ParagraphStyle('TocTitle', fontName=HEAD_FONT, fontSize=18, leading=26,
                            textColor=TEXT_PRIMARY, spaceAfter=12)


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def heading(text, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    style = S_H1 if level == 0 else (S_H2 if level == 1 else S_H3)
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def h1_block(text):
    return [CondPageBreak(H1_ORPHAN),
            heading(text, 0),
            HRFlowable(width='100%', thickness=1.2, color=ACCENT,
                       spaceBefore=0, spaceAfter=10)]


def body(text):
    return Paragraph(text, S_BODY)


def bullet(text):
    return Paragraph('• ' + text, S_BULLET)


def safe_keep(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def make_table(header, rows, ratios, caption=None, center_cols=None):
    center_cols = center_cols or set()
    data = [[Paragraph('<b>%s</b>' % c, S_TH) for c in header]]
    for r in rows:
        row = []
        for j, c in enumerate(r):
            st = S_TDC if j in center_cols else S_TD
            row.append(Paragraph(str(c), st))
        data.append(row)
    widths = [x * AVAIL_W for x in ratios]
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
             ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
             ('GRID', (0, 0), (-1, -1), 0.4, TEXT_MUTED),
             ('LEFTPADDING', (0, 0), (-1, -1), 6),
             ('RIGHTPADDING', (0, 0), (-1, -1), 6),
             ('TOPPADDING', (0, 0), (-1, -1), 4),
             ('BOTTOMPADDING', (0, 0), (-1, -1), 4)]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 10), t]
    if caption:
        out += [Spacer(1, 4), Paragraph(caption, S_CAPTION)]
    out.append(Spacer(1, 8))
    return out


def callout(big, label):
    t = Table([[Paragraph('<b>%s</b>' % big, S_STAT)],
               [Paragraph(label, S_STATL)]], colWidths=[170])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BG_SURFACE),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 10),
        ('TOPPADDING', (0, -1), (-1, -1), 2),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')]))
    return t


def callout_row(items):
    cells = [callout(b, l) for b, l in items]
    t = Table([cells], colWidths=[AVAIL_W / len(items)] * len(items), hAlign='CENTER')
    t.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                           ('ALIGN', (0, 0), (-1, -1), 'CENTER')]))
    return [Spacer(1, 8), t, Spacer(1, 8)]


def embed_fig(path, caption, max_w=None, max_h=250):
    max_w = max_w or AVAIL_W * 0.82
    pw, ph = PILImage.open(path).size
    ratio = min(max_w / pw, max_h / ph, 1.0)
    img = Image(path, width=pw * ratio, height=ph * ratio)
    img.hAlign = 'CENTER'
    return safe_keep([img, Paragraph(caption, S_CAPTION)])


def quote(text):
    t = Table([[Paragraph(text, S_QUOTE)]], colWidths=[AVAIL_W - 10])
    t.setStyle(TableStyle([
        ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
        ('BACKGROUND', (0, 0), (-1, -1), BG_PAGE),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6)]))
    return [Spacer(1, 6), t, Spacer(1, 6)]


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('SimHei', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - MARGIN + 14, '保肝中药成分虚拟筛选课题 · 详解与阶段结果说明')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - MARGIN + 8, PAGE_W - MARGIN, PAGE_H - MARGIN + 8)
    canvas.setStrokeColor(TEXT_MUTED)
    canvas.setLineWidth(0.4)
    canvas.line(MARGIN, MARGIN - 16, PAGE_W - MARGIN, MARGIN - 16)
    canvas.setFont('SimHei', 7.5)
    canvas.drawString(MARGIN, MARGIN - 28, '课题组：王启龙 宁显泷 衣思淼 代维斯丹 王散曼')
    canvas.drawRightString(PAGE_W - MARGIN, MARGIN - 28, '第 %d 页' % doc.page)
    canvas.restoreState()


# ════════════════════════ 正文内容 ════════════════════════
story = []

# 目录页
story.append(Paragraph('<b>目 录</b>', S_TOCTITLE))
toc = TableOfContents()
toc.levelStyles = [S_TOC0, S_TOC1]
story.append(toc)
story.append(PageBreak())

# ── 1 项目概述 ──
story.extend(h1_block('1 项目概述'))
story.append(heading('1.1 背景与目标', 1))
story.append(body('中药及其天然产物是保肝药物发现的重要分子来源，但传统"单一成分逐一实验"的筛选模式成本高、周期长。'
                  '本课题构建一条"计算优先"的虚拟筛选流水线：把中药成分转化为分子图，用图神经网络（GNN）预测保肝活性，'
                  '并用蒙特卡洛Dropout（MC Dropout）量化每次预测的不确定性；同时以分子对接提供物理维度的交叉验证，'
                  '最终把两类证据融合成协同评分排名，供后续湿实验按优先级验证。'))
story.append(body('暑期阶段的定位是"中期"：完成本地小样本全流程跑通与阶段结果产出，服务器上量与真实对接留待下一阶段。'
                  '全部计算结果由固定随机种子驱动，一键复现（本地全流程约 6 秒）。'))
story.extend(callout_row([('6.2 秒', '本地全流程复现耗时'),
                          ('60 个', '候选分子最终排名'),
                          ('AUC 0.967', 'GNN 测试集判别力'),
                          ('ρ = 0.718', '不确定性与误差相关性')]))

story.append(heading('1.2 技术路线', 1))
story.append(body('技术路线按"数据—算法—验证—融合"四段组织，各段职责与产物如下表。'))
story.extend(make_table(
    ['阶段', '核心动作', '产物'],
    [['数据', 'SMILES解析校验、规范化去重、Murcko骨架签名、骨架级划分、二维描述符计算',
      '清洗集88条 + 筛选池12条 + 描述符表'],
     ['算法', '分子图节点特征构建、2层GCN训练、MC Dropout推理、加权BCE损失权重选择',
      '预测均值 + 方差（test与全候选池）'],
     ['验证', '描述符+朴素贝叶斯、指纹+逻辑回归双基准线；FXR与Keap1双靶点对接评分（演示模式）',
      '基准线指标表 + 对接分表'],
     ['融合', '方差转置信度、与对接名次分、类药性分加权融合；适用域域外降权',
      '60候选协同评分排名总表 + 4张结果图']],
    [0.10, 0.52, 0.38], caption='表 1-1 技术路线四阶段与产物'))

story.append(heading('1.3 交付物清单', 1))
story.extend(make_table(
    ['类别', '文件/位置', '说明'],
    [['排名总表', 'results/rankings/final_ranking.csv', '60候选，含模型分/方差/置信/对接/域外标记'],
     ['模型预测', 'results/predictions/fullpool_predictions.csv', '全候选池均值+方差；test_predictions.csv 为测试集'],
     ['指标', 'results/metrics/baseline.csv、reliability_curve.csv', '基准线与GNN指标、可靠性曲线数据'],
     ['结果图', 'results/figures/*.png', '可靠性图、不确定性-误差、Top-15条形图、模型-对接散点'],
     ['文档', 'docs/、literature/、reports/midterm_report.md', '数据字典、环境、模型与对接说明、文献库、中期报告'],
     ['代码', 'src/ + run_all.py', '全部模块一键运行入口']],
    [0.16, 0.40, 0.44], caption='表 1-2 阶段交付物一览'))

# ── 2 团队分工 ──
story.extend(h1_block('2 团队分工与协作机制'))
story.append(heading('2.1 六周三段式分工', 1))
story.extend(make_table(
    ['成员', '前两周（环境与数据）', '中间两周（全量与出分）', '最后两周（收敛与闭环）'],
    [['王启龙', 'git仓库、零依赖环境方案、首批数据跑通', '数据过滤与适用域预警代码、批量对接脚本', '排名自动化脚本、结果图、中期材料归档'],
     ['宁显泷', 'SMILES转分子图解析器、GNN结构定型', '图数据集构建、MC Dropout推理、损失权重选择', '模型冻结后全候选池批量推理'],
     ['衣思淼', '数据库调研、清洗接口设计、测试数据交付', '全量去重与骨架统一、描述符、适用域边界', '方差转置信度、协同评分矩阵、排名总表'],
     ['代维斯丹', '对接引擎与可视化工具配置', '双基准线训练、受体网格盒子参数、批量对接', '高精度复核（演示模式）、可靠性评估'],
     ['王散曼', '经典保肝成分候选池（48+40）与证据标注', '萜类/木脂素新分子池（12条）与成药性记录', 'Top候选文献溯源、药效团归纳']],
    [0.11, 0.28, 0.31, 0.30], caption='表 2-1 成员×阶段分工矩阵'))
story.append(heading('2.2 协作与版本管理', 1))
story.append(body('仓库按模块归属做作者署名提交，git 历史共 8 次提交、5 位作者，与分工矩阵一一对应；'
                  '联合任务（适用域、评分融合、出图）以"主责+协作"双作者记录。'
                  '三次组会纪要（docs/minutes/）记录了各节点验收结论与关键决议，包括不确定性方案二选一（MC Dropout 对比模型集成）、'
                  '损失权重选择规则、阳性参照药排名偏低的原因分析等。'))

# ── 3 数据体系 ──
story.extend(h1_block('3 数据体系详解'))
story.append(heading('3.1 数据集构成', 1))
story.extend(make_table(
    ['子集', '编号前缀', '数量', '用途'],
    [['保肝活性分子', 'HP', '48', '正样本，覆盖黄酮/三萜/木脂素/蒽醌/环烯醚萜苷/生物碱/香豆素等类别'],
     ['负参照', 'DC', '40', '惰性小分子 + 无保肝证据西药 + 经典肝毒性药物（难负样本）'],
     ['新分子筛选池', 'NV', '12', '结构较新颖的萜类/木脂素 + 奥贝胆酸作方法学阳性参照'],
     ['合计', 'HP/DC/NV', '100', '原始输入，清洗后88条带标签 + 12条无标签筛选池']],
    [0.20, 0.12, 0.10, 0.58], center_cols={1, 2}, caption='表 3-1 数据集构成'))
story.append(body('负样本刻意引入对乙酰氨基酚、异烟肼、丙戊酸、氯霉素、甲氨蝶呤等经典肝毒性药物，构成"难负样本"：'
                  '迫使模型学习"结构是否保肝"的本质规律，而不是简单区分"天然产物与合成药物"的表面特征。'))
story.append(heading('3.2 标签口径与证据分级', 1))
story.append(body('标签定义为"是否存在保肝活性的公开证据"（二分类），而非活性强度。证据分级：A 级代表临床研究/系统评价'
                  '或已上市保肝制剂的主要成分（如水飞蓟宾、甘草酸、姜黄素）；B 级代表至少两类肝损伤动物模型支持；'
                  'C 级代表单次动物或细胞实验支持。每条正样本附一句话证据摘要，便于溯源。'))
story.append(heading('3.3 清洗管线', 1))
story.extend(make_table(
    ['步骤', '规则', '结果'],
    [['解析校验', '自研SMILES解析器逐条建图，失败即剔除并留痕 rejected.csv', '首版曾剔除22条五环三萜（环号未闭合），修正后重新入库'],
     ['规范化去重', 'DFS重编号规范串作为键，重复结构只保留首条', '当前0条重复'],
     ['骨架签名', '迭代剪除度小于等于1的原子，剩余子图即Murcko骨架（近似）', '53个骨架组，含1个无环组（糖类负参照）'],
     ['描述符计算', '7维二维描述符（见3.5节）', '追加至清洗表'],
     ['骨架级划分', '以骨架组为单位贪心装入test(约20%)/val(约15%)/train(其余)', 'train 58（正28）/ val 13（正8）/ test 17（正12）']],
    [0.14, 0.46, 0.40], caption='表 3-2 清洗管线五步'))
story.append(body('骨架级划分的意义：同一骨架的分子绝不跨集合，防止"训练集见过芹菜素、测试集考木犀草素"式的骨架泄漏，'
                  '让测试指标反映真实的结构外推能力。'))
story.append(heading('3.4 二维描述符口径', 1))
story.extend(make_table(
    ['描述符', '计算口径', '备注'],
    [['MW', '原子量加和（含隐式氢）', '三萜简化骨架系统性偏高约5%-10%'],
     ['logP_est', '原子贡献法（截距-0.55，芳香修正+0.12/体系，MW大于650渗透罚-0.5）', '演示级，服务器端换Crippen'],
     ['TPSA_est', 'N/O原子贡献近似（O约20.2，N约12.5，极性氢+1.5）', '演示级'],
     ['nHBD / nHBA', '带氢O/N计数 / 中性O+N计数', ' Lipinski口径'],
     ['nRot', '非环重原子单键且两端度大于1', ''],
     ['nAromSystems', '芳香原子子图连通分量数（稠环计为1）', '']],
    [0.18, 0.52, 0.30], caption='表 3-3 7维描述符定义'))
story.append(heading('3.5 适用域（AD）判定', 1))
story.append(Paragraph('以训练集7维标准化描述符计算杠杆值 h<sub>i</sub> = x<sub>i</sub><super>T</super>(X<super>T</super>X)<super>-1</super>x<sub>i</sub>，'
                        '阈值取 h* = 3p/n = 3×7/58 = 0.362。超过阈值的分子在最终排名中打"域外"标记并乘以0.9预警降权。', S_BODY_NI))
story.append(body('筛选池12个新分子中7个（以三萜酸类为主）被正确标记域外——训练集三萜样本少、结构新颖度高的分子'
                  '自动降权，机制符合设计预期。'))

# ── 4 方法详解 ──
story.extend(h1_block('4 模型方法详解'))
story.append(heading('4.1 分子图表征', 1))
story.append(body('SMILES 经自研解析器转为"原子为节点、键为边"的分子图（纯Python实现，无RDKit依赖）。'
                  '节点特征13维：元素one-hot（C/N/O/S/P/F/Cl/Br/I/B共10维）+ 芳香标记 + 归一化度数 + 归一化氢数。'
                  '邻接矩阵加入自环后做对称归一化 D<super>-1/2</super>(A+I)D<super>-1/2</super>，稳定消息传递的数值尺度。'))
story.append(heading('4.2 网络结构', 1))
story.append(Paragraph('H<super>(1)</super> = tanh( D<super>-1/2</super>(A+I)D<super>-1/2</super> · X · W<sub>1</sub> + b<sub>1</sub> )', S_BODY_NI))
story.append(Paragraph('第一层输出经同样的消息传递进入第二层同构GCN（隐层为32维与16维）。'
                        '两层消息传递结束后对节点向量做均值池化以得到图级表征。'
                        '池化向量经Dropout(0.3)随机失活后送入线性输出层并取sigmoid得到保肝概率。'
                        '优化器采用Adam：学习率0.01、权重衰减系数1×10<super>-4</super>、全批量训练300轮。', S_BODY))
story.append(heading('4.3 MC Dropout 不确定性估计', 1))
story.append(body('推理时不关闭Dropout，前向 T=30 次，得到一组预测概率 {p<sub>1</sub>, …, p<sub>T</sub>}。'
                  '取均值 pred_mean 作为最终预测，取方差 pred_var 作为认知不确定性的近似：方差大意味着"网络对这类结构没把握"，'
                  '而不是简单的置信度低。方案在组会上与"5模型集成"二选一：小样本下两者不确定性质量接近，MC Dropout零额外训练成本，故选用之。'))
story.append(heading('4.4 损失权重实验', 1))
story.append(body('正类权重 w<sub>pos</sub> 在 {1.0, 1.25, 1.5} 中按验证集F1选优，同分时取更保守的小权重：'))
story.extend(make_table(
    ['w_pos', '1.0', '1.25（选用）', '1.5'],
    [['验证集F1', '0.625', '0.667', '0.667']],
    [0.31, 0.23, 0.23, 0.23], center_cols={1, 2, 3}, caption='表 4-1 加权BCE正类权重选择'))
story.append(heading('4.5 传统机器学习基准线', 1))
story.append(body('为GNN提供可比基准的两条传统线：(1) 7维描述符 + 高斯朴素贝叶斯；(2) 2048bit哈希环形指纹（Morgan型，'
                  'MD5哈希保证跨平台确定性）+ L2正则逻辑回归。基准线在GNN之前出分，保证最终能并表对比。'))
story.append(heading('4.6 分子对接（本地演示模式）', 1))
story.extend(make_table(
    ['靶点', 'PDB', '口袋类型', '盒子中心(Å)', '盒子尺寸(Å)', '参考配体'],
    [['FXR-LBD', '1OSH', '疏水型', '15.2, 3.8, 24.5', '22×22×24', 'fexaramine'],
     ['Keap1-Kelch', '2FLU', '极性/碱性', '-11.5, 20.4, -6.2', '20×20×20', 'Nrf2 ETGE肽']],
    [0.17, 0.10, 0.13, 0.22, 0.18, 0.20], center_cols={1, 2, 3, 4}, caption='表 4-2 双靶点与网格盒子参数'))
story.append(body('本地演示机未部署AutoDock Vina，对接分由物理启发打分函数替代：按口袋类型对描述符做加权线性组合'
                  '（FXR偏好高logP与芳香体系，Keap1偏好氢键供受体），加MW大于550的渗透罚与按"分子+靶点"哈希种子的'
                  '固定噪声（σ=0.35），标定到 kcal/mol 量级。自检区分度：FXR上活性分子均分-5.46 对 负参照-5.05 kcal/mol。'
                  '该分数仅用于排序流程验证，服务器端运行 run_vina.sh 复算后直接覆盖同名列，下游无需改动。'))
story.append(heading('4.7 协同评分融合', 1))
story.append(Paragraph('final = 0.45 × model_term + 0.35 × dock_term + 0.20 × dl_term，其中：'
                        'model_term = pred_mean × (0.5 + 0.5 × confidence)，confidence = 1 - min(1, √var / 0.25)；'
                        'dock_term = 1 - rank_pct（两靶点对接分均值的名次百分位，结合越强分越高）；'
                        'dl_term = 1 - 0.25 × Lipinski违规数；适用域外分子再乘0.9预警降权。', S_BODY_NI))

# ── 5 阶段结果 ──
story.extend(h1_block('5 阶段结果详解'))
story.append(heading('5.1 模型对比', 1))
story.extend(make_table(
    ['模型', 'AUC', 'ACC', 'BACC', 'F1'],
    [['高斯朴素贝叶斯（描述符）', '0.850', '0.706', '0.733', '0.762'],
     ['逻辑回归（2048bit指纹）', '0.967', '0.706', '0.792', '0.737'],
     ['GNN + MC Dropout（本课题）', '0.967', '0.824', '0.875', '0.857']],
    [0.40, 0.15, 0.15, 0.15, 0.15], center_cols={1, 2, 3, 4}, caption='表 5-1 测试集指标对比（n=17，正12）'))
story.append(body('GNN与指纹逻辑回归的AUC持平，但平衡准确率与F1明显更优（0.875/0.857 对 0.792/0.737）：'
                  '小样本下图结构表征学到的分类边界更稳。朴素贝叶斯受描述符维度过低限制，作为"下界"参照。'))
story.extend(embed_fig(os.path.join(FIG, 'model_dock_scatter.png'),
                       '图 5-1 模型预测分与对接分的一致性散点（叉号=适用域外分子）', max_h=235))
story.append(heading('5.2 不确定性与校准', 1))
story.append(body('不确定性质量：预测方差与绝对误差的Spearman相关 ρ = 0.718，说明方差确实在"给错得离谱的预测打高分"，'
                  '置信度加权有据可依。校准偏差：ECE（10桶）= 0.210，模型整体偏"过自信"——预测概率系统性靠近0或1，'
                  '但实际错误率高于其自报置信。这是如实呈现的中期发现，已列入下一阶段温度校准任务（目标ECE小于0.10）。'))
story.extend(embed_fig(os.path.join(FIG, 'reliability_diagram.png'),
                       '图 5-2 可靠性图：预测概率分桶与实际正确率（虚线为完美校准）', max_h=235))
story.extend(embed_fig(os.path.join(FIG, 'uncertainty_vs_error.png'),
                       '图 5-3 MC Dropout方差与预测误差的关系（正相关即不确定性有效）', max_h=235))
story.append(heading('5.3 适用域的方法论发现', 1))
story.extend(quote('阳性参照药奥贝胆酸（FXR激动剂，临床用药）模型分仅0.26且被判域外——训练集是中药成分化学空间，'
                   '甾体骨架不在其中。结论：模型分只在中药化学空间内可解释；跨空间筛选必须依赖对接分与适用域标记，'
                   '这正是三源融合评分的价值所在。'))
story.append(heading('5.4 最终排名（60候选，节选Top-10）', 1))
story.extend(make_table(
    ['排名', '候选', '类别', '模型分', '方差', '置信', '对接(kcal/mol)', '域外', '总评'],
    [['1', '黄芩苷', '黄酮苷', '0.9612', '0.0012', '0.863', '-6.86', '否', '0.9291'],
     ['2', '二氢杨梅素', '黄酮醇', '0.9653', '0.0017', '0.837', '-7.14', '否', '0.8990'],
     ['3', '葛根素', '异黄酮苷', '0.9614', '0.0018', '0.832', '-7.03', '否', '0.8903'],
     ['4', '姜黄素', '多酚', '0.8898', '0.0050', '0.718', '-6.94', '否', '0.8821'],
     ['5', '柚皮素', '黄烷酮', '0.9413', '0.0021', '0.815', '-6.54', '否', '0.8811'],
     ['6', '木犀草素', '黄酮', '0.9783', '0.0008', '0.887', '-6.43', '否', '0.8704'],
     ['7', '水飞蓟宾', '黄酮木脂素', '0.9666', '0.0011', '0.869', '-6.39', '否', '0.8497'],
     ['8', '松脂素（新）', '呋喃木脂素', '0.8814', '0.0068', '0.670', '-6.64', '否', '0.8397'],
     ['9', '槲皮素', '黄酮醇', '0.9718', '0.0031', '0.776', '-6.37', '否', '0.8198'],
     ['10', '落叶松脂素（新）', '开环木脂素', '0.7912', '0.0097', '0.606', '-6.89', '否', '0.8181']],
    [0.08, 0.17, 0.13, 0.10, 0.10, 0.08, 0.14, 0.08, 0.12],
    center_cols={0, 3, 4, 5, 6, 7, 8}, caption='表 5-2 协同评分Top-10（完整60条见 results/rankings/final_ranking.csv）'))
story.extend(embed_fig(os.path.join(FIG, 'top_candidates.png'),
                       '图 5-4 Top-15候选总评条形图', max_h=260))
story.append(body('排名体系的事后合理性佐证：临床金标准保肝药水飞蓟宾落在第7位；木犀草素在Top-10中拿到最高模型分与最低方差（0.978/0.0008）。'
                  '新分子方面，松脂素（第8）与落叶松脂素（第10）进入Top-10，置信度与域内状态合理——'
                  '木脂素支线在训练集中有五味子、厚朴、牛蒡子等来源，模型对该骨架的外推可信。'
                  '三萜酸类新分子（积雪草酸、科罗索酸、马斯里酸等）模型置信度普遍偏低且多为域外，符合训练集三萜样本稀少的预期。'
                  '另需说明：全场最高模型分与最低方差并不出现在Top-10内——大黄素模型分0.993、苦参碱MC方差约1.2×10<super>-5</super>，'
                  '但二者的对接分与类药性拉低了总评，这恰好印证了三源融合而非单看模型分的必要性。'))
story.append(heading('5.5 药效团归纳（Top-10共性）', 1))
story.extend(make_table(
    ['药效团要素', '命中', '对应机制'],
    [['多酚羟基特征（每分子至少2个酚羟基）', '10/10（6/10含间/邻二酚）', '抗氧化清除自由基；Keap1口袋氢键网络'],
     ['双芳香环体系（黄酮/木脂素核心）', '10/10', 'FXR疏水口袋π堆积（fexaramine等排替代）'],
     ['C6-C3-C6或木脂素二聚骨架', '9/10（姜黄素例外）', '连接区提供刚性疏水核心，末端酚羟基作极性锚点'],
     ['三萜酸C-28羧基+3β-OH', '独立支线', 'FXR胆酸口袋等排（奥贝胆酸成药化路径）']],
    [0.36, 0.22, 0.42], center_cols={1}, caption='表 5-3 Top-10药效团要素归纳'))

# ── 6 复现指南 ──
story.extend(h1_block('6 复现指南'))
story.append(heading('6.1 环境要求', 1))
story.append(body('本地零依赖策略：只需 Python 3.9+ 与 numpy（matplotlib可选，仅出图用）。'
                  'SMILES解析、描述符、指纹、GNN全部为纯numpy实现，任何成员的笔记本都可跑通；'
                  '服务器端迁移清单见 docs/00_environment.md（RDKit/PyTorch/Vina）。'))
story.append(heading('6.2 一键运行', 1))
story.append(Paragraph('cd hepato-gnn-screening && python run_all.py', S_CODE))
story.extend(make_table(
    ['阶段', '控制台输出要点', '耗时'],
    [['1 数据清洗', '带标签集88条（正48/负40）；筛选池12条；剔除0条', '小于1秒'],
     ['2 骨架划分', 'train 58 / val 13 / test 17；骨架组53个', '小于1秒'],
     ['3 基准线', 'NB与LR的AUC/ACC/BACC/F1', '约1秒'],
     ['4 GNN+MC Dropout', 'w_pos选择过程与测试集指标、ρ值', '约4秒'],
     ['5 对接演示', '双靶点盒子参数与区分度自检', '小于1秒'],
     ['6 适用域', 'h*阈值与域外分子计数', '小于1秒'],
     ['7 评分融合', '60候选入库与Top-10打印', '小于1秒'],
     ['8 结果图', '4张PNG输出', '约1秒']],
    [0.22, 0.58, 0.20], caption='表 6-1 run_all.py 八个阶段'))
story.append(body('全部随机过程固定种子（训练seed=7/42、划分seed=42、对接噪声按分子ID哈希），重跑结果完全一致；'
                  'CSV统一UTF-8编码，读取用 utf-8-sig。'))

# ── 7 复核清单 ──
story.extend(h1_block('7 复核清单与下一阶段'))
story.append(heading('7.1 结果诚实性分级', 1))
story.extend(make_table(
    ['事项', '状态', '复核方式'],
    [['模型指标（AUC/F1/ECE等）', '本地真实计算', 'python run_all.py 可复现'],
     ['不确定性/适用域/协同评分', '本地真实计算', '同上'],
     ['对接评分', '演示模式（物理启发占位）', '服务器 run_vina.sh 复算覆盖'],
     ['种子集SMILES', '教学复现版（三萜/苷类有简化）', 'TCMSP/PubChem导出替换'],
     ['文献引用', '调研整理稿', '逐条核对原文后引用']],
    [0.34, 0.30, 0.36], caption='表 7-1 复核清单'))
story.append(heading('7.2 下一阶段计划', 1))
story.append(bullet('服务器迁移：RDKit/PyG版模型 + Vina真实对接，覆盖演示分；'))
story.append(bullet('数据扩充：数据库正式导出，目标不少于1000条带标签分子，收敛测试集置信区间；'))
story.append(bullet('校准修复：温度系数法把ECE从0.210压到0.10以下；'))
story.append(bullet('实验衔接：松脂素、落叶松脂素（Top-10新分子）优先推进体外验证与深度文献挖掘；'))
story.append(bullet('证据升级：把A/B/C证据分级折算为序数标签，从分类走向活性强度回归。'))
story.append(Spacer(1, 16))
story.append(Paragraph('全文完', ParagraphStyle('End', parent=S_CAPTION, fontSize=10)))

doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN + 6, bottomMargin=MARGIN + 10,
    title='保肝中药成分虚拟筛选课题·详解与阶段结果说明',
    author='Z.ai', creator='Z.ai',
    subject='GNN+MC Dropout保肝中药成分虚拟筛选：方法详解与中期阶段结果')
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body.pdf built:', OUT)
